#!/usr/bin/env python

import sys

# from rqt_movr_speech_rec.movr_speech_rec_module import MOVRSpeechRecPlugin
from movr_speech_rec_module import MOVRSpeechRecPlugin
from rqt_gui.main import Main

plugin = 'rqt_movr_speech_rec'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))